/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGithubPublicSplatRouteImport } from './routes/api/github/public/$'
import { Route as HostOwnerRepoPullNumberRouteImport } from './routes/$host.$owner.$repo.pull.$number'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubPublicSplatRoute = ApiGithubPublicSplatRouteImport.update({
  id: '/api/github/public/$',
  path: '/api/github/public/$',
  getParentRoute: () => rootRouteImport,
} as any)
const HostOwnerRepoPullNumberRoute = HostOwnerRepoPullNumberRouteImport.update({
  id: '/$host/$owner/$repo/pull/$number',
  path: '/$host/$owner/$repo/pull/$number',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/github/public/$': typeof ApiGithubPublicSplatRoute
  '/$host/$owner/$repo/pull/$number': typeof HostOwnerRepoPullNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/github/public/$': typeof ApiGithubPublicSplatRoute
  '/$host/$owner/$repo/pull/$number': typeof HostOwnerRepoPullNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/github/public/$': typeof ApiGithubPublicSplatRoute
  '/$host/$owner/$repo/pull/$number': typeof HostOwnerRepoPullNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/github/public/$' | '/$host/$owner/$repo/pull/$number'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/github/public/$' | '/$host/$owner/$repo/pull/$number'
  id:
    | '__root__'
    | '/'
    | '/api/github/public/$'
    | '/$host/$owner/$repo/pull/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGithubPublicSplatRoute: typeof ApiGithubPublicSplatRoute
  HostOwnerRepoPullNumberRoute: typeof HostOwnerRepoPullNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/public/$': {
      id: '/api/github/public/$'
      path: '/api/github/public/$'
      fullPath: '/api/github/public/$'
      preLoaderRoute: typeof ApiGithubPublicSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$host/$owner/$repo/pull/$number': {
      id: '/$host/$owner/$repo/pull/$number'
      path: '/$host/$owner/$repo/pull/$number'
      fullPath: '/$host/$owner/$repo/pull/$number'
      preLoaderRoute: typeof HostOwnerRepoPullNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGithubPublicSplatRoute: ApiGithubPublicSplatRoute,
  HostOwnerRepoPullNumberRoute: HostOwnerRepoPullNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
