/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealthRouteImport } from './routes/health'
import { Route as FramesMermaidRouteImport } from './routes/frames.mermaid'
import { Route as FramesRendererRouteImport } from './routes/frames.renderer'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiGithubInstallRouteImport } from './routes/api/github/install'
import { Route as ApiGithubSetupRouteImport } from './routes/api/github/setup'
import { Route as ApiGithubWebhookRouteImport } from './routes/api/github/webhook'
import { Route as ApiGithubPublicSplatRouteImport } from './routes/api/github/public/$'
import { Route as ApiGithubUserSplatRouteImport } from './routes/api/github/user/$'
import { Route as ApiGithubWriteSplatRouteImport } from './routes/api/github/write/$'
import { Route as HostOwnerRepoPullNumberRouteImport } from './routes/$host.$owner.$repo.pull.$number'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const FramesMermaidRoute = FramesMermaidRouteImport.update({
  id: '/frames/mermaid',
  path: '/frames/mermaid',
  getParentRoute: () => rootRouteImport,
} as any)
const FramesRendererRoute = FramesRendererRouteImport.update({
  id: '/frames/renderer',
  path: '/frames/renderer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubInstallRoute = ApiGithubInstallRouteImport.update({
  id: '/api/github/install',
  path: '/api/github/install',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubSetupRoute = ApiGithubSetupRouteImport.update({
  id: '/api/github/setup',
  path: '/api/github/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubWebhookRoute = ApiGithubWebhookRouteImport.update({
  id: '/api/github/webhook',
  path: '/api/github/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubPublicSplatRoute = ApiGithubPublicSplatRouteImport.update({
  id: '/api/github/public/$',
  path: '/api/github/public/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubUserSplatRoute = ApiGithubUserSplatRouteImport.update({
  id: '/api/github/user/$',
  path: '/api/github/user/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubWriteSplatRoute = ApiGithubWriteSplatRouteImport.update({
  id: '/api/github/write/$',
  path: '/api/github/write/$',
  getParentRoute: () => rootRouteImport,
} as any)
const HostOwnerRepoPullNumberRoute = HostOwnerRepoPullNumberRouteImport.update({
  id: '/$host/$owner/$repo/pull/$number',
  path: '/$host/$owner/$repo/pull/$number',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/frames/mermaid': typeof FramesMermaidRoute
  '/frames/renderer': typeof FramesRendererRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/install': typeof ApiGithubInstallRoute
  '/api/github/setup': typeof ApiGithubSetupRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/github/public/$': typeof ApiGithubPublicSplatRoute
  '/api/github/user/$': typeof ApiGithubUserSplatRoute
  '/api/github/write/$': typeof ApiGithubWriteSplatRoute
  '/$host/$owner/$repo/pull/$number': typeof HostOwnerRepoPullNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/frames/mermaid': typeof FramesMermaidRoute
  '/frames/renderer': typeof FramesRendererRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/install': typeof ApiGithubInstallRoute
  '/api/github/setup': typeof ApiGithubSetupRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/github/public/$': typeof ApiGithubPublicSplatRoute
  '/api/github/user/$': typeof ApiGithubUserSplatRoute
  '/api/github/write/$': typeof ApiGithubWriteSplatRoute
  '/$host/$owner/$repo/pull/$number': typeof HostOwnerRepoPullNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/frames/mermaid': typeof FramesMermaidRoute
  '/frames/renderer': typeof FramesRendererRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/install': typeof ApiGithubInstallRoute
  '/api/github/setup': typeof ApiGithubSetupRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/github/public/$': typeof ApiGithubPublicSplatRoute
  '/api/github/user/$': typeof ApiGithubUserSplatRoute
  '/api/github/write/$': typeof ApiGithubWriteSplatRoute
  '/$host/$owner/$repo/pull/$number': typeof HostOwnerRepoPullNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/frames/mermaid'
    | '/frames/renderer'
    | '/api/auth/$'
    | '/api/github/install'
    | '/api/github/setup'
    | '/api/github/webhook'
    | '/api/github/public/$'
    | '/api/github/user/$'
    | '/api/github/write/$'
    | '/$host/$owner/$repo/pull/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/frames/mermaid'
    | '/frames/renderer'
    | '/api/auth/$'
    | '/api/github/install'
    | '/api/github/setup'
    | '/api/github/webhook'
    | '/api/github/public/$'
    | '/api/github/user/$'
    | '/api/github/write/$'
    | '/$host/$owner/$repo/pull/$number'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/frames/mermaid'
    | '/frames/renderer'
    | '/api/auth/$'
    | '/api/github/install'
    | '/api/github/setup'
    | '/api/github/webhook'
    | '/api/github/public/$'
    | '/api/github/user/$'
    | '/api/github/write/$'
    | '/$host/$owner/$repo/pull/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  FramesMermaidRoute: typeof FramesMermaidRoute
  FramesRendererRoute: typeof FramesRendererRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiGithubInstallRoute: typeof ApiGithubInstallRoute
  ApiGithubSetupRoute: typeof ApiGithubSetupRoute
  ApiGithubWebhookRoute: typeof ApiGithubWebhookRoute
  ApiGithubPublicSplatRoute: typeof ApiGithubPublicSplatRoute
  ApiGithubUserSplatRoute: typeof ApiGithubUserSplatRoute
  ApiGithubWriteSplatRoute: typeof ApiGithubWriteSplatRoute
  HostOwnerRepoPullNumberRoute: typeof HostOwnerRepoPullNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frames/mermaid': {
      id: '/frames/mermaid'
      path: '/frames/mermaid'
      fullPath: '/frames/mermaid'
      preLoaderRoute: typeof FramesMermaidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frames/renderer': {
      id: '/frames/renderer'
      path: '/frames/renderer'
      fullPath: '/frames/renderer'
      preLoaderRoute: typeof FramesRendererRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/install': {
      id: '/api/github/install'
      path: '/api/github/install'
      fullPath: '/api/github/install'
      preLoaderRoute: typeof ApiGithubInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/setup': {
      id: '/api/github/setup'
      path: '/api/github/setup'
      fullPath: '/api/github/setup'
      preLoaderRoute: typeof ApiGithubSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/webhook': {
      id: '/api/github/webhook'
      path: '/api/github/webhook'
      fullPath: '/api/github/webhook'
      preLoaderRoute: typeof ApiGithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/public/$': {
      id: '/api/github/public/$'
      path: '/api/github/public/$'
      fullPath: '/api/github/public/$'
      preLoaderRoute: typeof ApiGithubPublicSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/user/$': {
      id: '/api/github/user/$'
      path: '/api/github/user/$'
      fullPath: '/api/github/user/$'
      preLoaderRoute: typeof ApiGithubUserSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/write/$': {
      id: '/api/github/write/$'
      path: '/api/github/write/$'
      fullPath: '/api/github/write/$'
      preLoaderRoute: typeof ApiGithubWriteSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$host/$owner/$repo/pull/$number': {
      id: '/$host/$owner/$repo/pull/$number'
      path: '/$host/$owner/$repo/pull/$number'
      fullPath: '/$host/$owner/$repo/pull/$number'
      preLoaderRoute: typeof HostOwnerRepoPullNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  FramesMermaidRoute: FramesMermaidRoute,
  FramesRendererRoute: FramesRendererRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiGithubInstallRoute: ApiGithubInstallRoute,
  ApiGithubSetupRoute: ApiGithubSetupRoute,
  ApiGithubWebhookRoute: ApiGithubWebhookRoute,
  ApiGithubPublicSplatRoute: ApiGithubPublicSplatRoute,
  ApiGithubUserSplatRoute: ApiGithubUserSplatRoute,
  ApiGithubWriteSplatRoute: ApiGithubWriteSplatRoute,
  HostOwnerRepoPullNumberRoute: HostOwnerRepoPullNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
